/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/test': {
    post: operations['test_test_post'];
  };
  '/generate_design': {
    post: operations['generate_design_generate_design_post'];
  };
  '/get_design': {
    post: operations['get_design_get_design_post'];
  };
}

export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** ResponseGenerateDesign */
    ResponseGenerateDesign: {
      /** Design Id */
      design_id?: number;
      /** Design Uuid */
      design_uuid?: string;
      /** Qr Code Img */
      qr_code_img?: string;
      /** Shirt Img */
      shirt_img?: string;
      /** Elevation Map Img */
      elevation_map_img?: string;
      /** Lines Design Img */
      lines_design_img?: string;
      /** Edition Title */
      edition_title?: string;
      /** Edition Desc */
      edition_desc?: string;
      /** Is Success */
      is_success?: boolean;
      /** Error Code */
      error_code?: number;
      /** Error Desc */
      error_desc?: string;
    };
    /** ResponseGetDesign */
    ResponseGetDesign: {
      /** Design Id */
      design_id?: number;
      /** Design Uuid */
      design_uuid?: string;
      /** Title */
      title?: string;
      /** Description */
      description?: string;
      /** Qr Code Img */
      qr_code_img?: string;
      /** Shirt Img */
      shirt_img?: string;
      /** Elevation Map Img */
      elevation_map_img?: string;
      /** Normal Map Img */
      normal_map_img?: string;
      /** Is Success */
      is_success?: boolean;
      /** Edition Title */
      edition_title?: string;
      /** Edition Desc */
      edition_desc?: string;
      /** Error Code */
      error_code?: number;
      /** Error Desc */
      error_desc?: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: string[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
}

export interface operations {
  test_test_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  generate_design_generate_design_post: {
    parameters: {
      query: {
        api_key: string;
        is_preview: boolean;
        title: string;
        description: string;
        west: number;
        north: number;
        east: number;
        south: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ResponseGenerateDesign'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_design_get_design_post: {
    parameters: {
      query: {
        api_key: string;
        design_uuid: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ResponseGetDesign'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}

// export interface external { }
