/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/test': {
    post: operations['test_test_post'];
  };
  '/design': {
    get: operations['get_design_design_get'];
    post: operations['generate_design_design_post'];
  };
  '/user/register': {
    post: operations['register_user_user_register_post'];
  };
  '/user/login': {
    post: operations['login_user_user_login_post'];
  };
  '/create-payment-intent': {
    post: operations['create_checkout_session_create_payment_intent_post'];
  };
}

export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** ResponseGenerateDesign */
    ResponseGenerateDesign: {
      /** Design Id */
      design_id?: number;
      /** Design Uuid */
      design_uuid?: string;
      /** Qr Code Img */
      qr_code_img?: string;
      /** Shirt Img */
      shirt_img?: string;
      /** Elevation Map Img */
      elevation_map_img?: string;
      /** Lines Design Img */
      lines_design_img?: string;
      /** Edition Title */
      edition_title?: string;
      /** Edition Desc */
      edition_desc?: string;
      /** Is Success */
      is_success?: boolean;
      /** Error Code */
      error_code?: number;
      /** Error Desc */
      error_desc?: string;
    };
    /** ResponseGetDesign */
    ResponseGetDesign: {
      /** Design Id */
      design_id?: number;
      /** Design Uuid */
      design_uuid?: string;
      /** Title */
      title?: string;
      /** Description */
      description?: string;
      /** Qr Code Img */
      qr_code_img?: string;
      /** Shirt Img */
      shirt_img?: string;
      /** Elevation Map Img */
      elevation_map_img?: string;
      /** Normal Map Img */
      normal_map_img?: string;
      /** Is Success */
      is_success?: boolean;
      /** Edition Title */
      edition_title?: string;
      /** Edition Desc */
      edition_desc?: string;
      /** Error Code */
      error_code?: number;
      /** Error Desc */
      error_desc?: string;
    };
    /** ResponseLoginUser */
    ResponseLoginUser: {
      /** User Id */
      user_id?: string;
      /** Access Token */
      access_token?: string;
      /** Is Success */
      is_success?: boolean;
      /** Error Code */
      error_code?: number;
      /** Error Desc */
      error_desc?: string;
    };
    /** ResponsePaymentIntent */
    ResponsePaymentIntent: {
      /** Client Secret */
      client_secret?: string;
      /** Is Success */
      is_success?: boolean;
      /** Error Code */
      error_code?: number;
      /** Error Message */
      error_message?: string;
    };
    /** ResponseRegisterUser */
    ResponseRegisterUser: {
      /** User Id */
      user_id?: string;
      /** Is Success */
      is_success?: boolean;
      /** Error Code */
      error_code?: number;
      /** Error Desc */
      error_desc?: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: string[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
}

export interface operations {
  test_test_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  get_design_design_get: {
    parameters: {
      query: {
        api_key?: string;
        design_uuid?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ResponseGetDesign'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  generate_design_design_post: {
    parameters: {
      query: {
        api_key: string;
        is_preview: boolean;
        title: string;
        description: string;
        west: number;
        north: number;
        east: number;
        south: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ResponseGenerateDesign'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  register_user_user_register_post: {
    parameters: {
      query: {
        username: string;
        email: string;
        password: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ResponseRegisterUser'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  login_user_user_login_post: {
    parameters: {
      query: {
        email: string;
        password: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ResponseLoginUser'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_checkout_session_create_payment_intent_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ResponsePaymentIntent'];
        };
      };
    };
  };
}

export interface external {}
